### ISSUE TITLE
Lagom 1.4 support

### ISSUE THREAD

**Issue by olivierdeckers** [typesafehub/service-locator-dns#14]
When used with Lagom 1.4, we get the following exception:
`Exception in thread "main" java.lang.NoSuchMethodError: play.api.Environment.mode()Lscala/Enumeration$Value`

This is due to the change to Environment.mode in Play2.6: https://www.playframework.com/documentation/2.6.x/Migration26#Scala-Mode-changes

In order to support Lagom 1.4, it seems no additional changes are needed except from a version that was compiled with Play 2.6. 

We are prepared to create a pull request. Do you want this as additional modules for lagom14?

**Comment by huntc** [comment]
This is known, but thanks. See how we have the `lagom13` projects - we'll need the same for `lagom14`. :-)
