### ISSUE TITLE
Lagom 1.4 release

### ISSUE THREAD

**Issue by stijndehaes** [typesafehub/service-locator-dns#16]
I see there is support for lagom 1.4 in the repo. But it is not yet published. Is it possible to publish for lagom1.4 as well? Or are you waiting for the release of lagom 1.4? We would like it to be available for testing lagom 1.4

**Comment by fsat** [comment]
@stijndehaes - it's definitely possible to release the lagom 1.4 support. I'll ping you once it's released.

**Comment by fsat** [comment]
@stijndehaes - I've created PR #17 - once this is reviewed and merged, I will cut a new release which will include Lagom 1.4 modules too.

**Comment by fsat** [comment]
@stijndehaes - we've just released Service Locator DNS `2.1.1` which contains the Lagom 1.4. Once the Maven sync is done, you should be able to get the library.
