### ISSUE TITLE
Make release and artifact based on lagom 1.2.0

### ISSUE THREAD

**Issue by kondratovich** [typesafehub/service-locator-dns#6]
There is a release Lagom with version 1.2.0. Can you update dependencies and version and push artifacts based on Lagom 1.2.0?

**Comment by huntc** [comment]
I can, but it should already be binary compatible. Have you found issues?

**Comment by kondratovich** [comment]
I've made simple test with Cassandra location. I have local running DNS server. Service locator works fine.

DNS Records:
```
_cas_native._tcp.andrew 9042 127.0.0.1
```

Service configuration:
```
#
# Copyright (C) 2016 Lightbend Inc. <http://www.lightbend.com>
#
play.modules.enabled += me.kondratovich.generator.impl.IdGeneratorModule

akka.io.dns {
  resolver = async-dns
  async-dns {
    resolve-srv = true
    nameservers = ["127.0.0.1"]
  }
}


service-locator-dns {
  name-translators = [
    {
      "^.*$" = "_$0._tcp.andrew"
    }
  ]

  name-translators = ${?SERVICE_LOCATOR_DNS_NAME_TRANSLATORS}
}
```

**Comment by huntc** [comment]
Nice! I'll close this then as there is no issue per se.
