### ISSUE TITLE
Http-protocol based service is not correctly discovered

### ISSUE THREAD

**Issue by rrybalkin** [typesafehub/service-locator-dns#7]
Our kubernetes cluster has a service with exposed http port 80. According to SRV name translators the corresponding record looks like `_http._tcp.my-svc.my-namespace.svc.cluster.local`
Service record is discovered and DNS name resolved into IP, but final address is `tcp://10.20.30.220:80`, when `http://10.20.30.220:80` expected.

Had a look into the code and realized that protocol prefix is defined by function [protocolFromName](https://github.com/typesafehub/service-locator-dns/blob/master/service-locator-dns/src/main/scala/com/lightbend/dns/locator/ServiceLocator.scala#L82), which extracts protocol from SRV record name, thus it places "tcp" prefix. But, SRV record for service `_http._http.my-svc.my-namespace.svc.cluster.local` cannot be found.

What is the way out that angle?

**Comment by huntc** [comment]
This library is following the standard convention of `_service._proto.name` as per [RFC 2782](https://tools.ietf.org/html/rfc2782).

**Comment by huntc** [comment]
Closing for now - I don't see this as a problem for this library. Please let me know if you feel otherwise or whether I've overlooked something.

**Comment by rrybalkin** [comment]
Do not argue with a fact that it's not issue for library, but it seems a restriction of it. 
Could you consider an improvement, an extension point in advanced configuration, for example some kind of translators for resolved address? Guess it's not too hard, but such improvement would allow us translate `tcp://10.20.30.220:80` into `http://10.20.30.220:80`

**Comment by huntc** [comment]
Sure, I'd consider a translation. Do you want to give it a go?

**Comment by rrybalkin** [comment]
Unfortunately, I'm not familiar with Scala. From my side happy to provide any help besides coding :-)
