### ISSUE TITLE
Provide Scala API for service-locator-dns

### ISSUE THREAD

**Issue by aantoniadis** [typesafehub/service-locator-dns#8]
Following up the discussion in https://groups.google.com/forum/#!topic/lagom-framework/PoVQKxhURt0 I believe that it would be useful to have service-locator-dns support for Scala.

**Comment by dpalinic** [comment]
+1 for this :)

**Comment by huntc** [comment]
@aantoniadis @dpalinic Your wish is my command: #13 

@davecromberge Not quite Scala 2.12, but an update for Lagom usage in case you're using it... 2.12 support will be incorporated once Lagom updates (1.4).

**Comment by aantoniadis** [comment]
@huntc thank you!

**Comment by dpalinic** [comment]
Awesome. Thanks @huntc :)
